---
prefer_indep_over_os_packages: false
osdeps_mode: all
apt_dpkg_update: false
GITHUB: http,ssh
GITHUB_ROOT: https://github.com
GITHUB_PUSH_ROOT: 'git@github.com:'
GITHUB_PRIVATE_ROOT: 'git@github.com:'
DFKIGIT: http,ssh
DFKIGIT_ROOT: https://git.hb.dfki.de
DFKIGIT_PUSH_ROOT: 'git@git.hb.dfki.de:'
DFKIGIT_PRIVATE_ROOT: 'git@git.hb.dfki.de:'
NDLCOM_ROBOTCONFIG: CommonConfig
ROCK_SELECTED_FLAVOR: master
ROCK_FLAVOR: master
ROCK_BRANCH: master
typelib_cxx_loader: castxml
USE_PYTHON: false
syskit_use_bundles: true
USE_OCL: false
rtt_target: gnulinux
rtt_corba_implementation: omniorb
