#!/bin/bash

set -e

cd /opt/workspace
if [ -z "$(find -maxdepth 1 -type d -name autoproj)" ] && [ -z "$(find -maxdepth 1 -type d -name src)" ]; then
    echo "Neither autoproj nor ros workspace detected."
    [ -z "$(ls -A)" ] && echo "Your workspace directory is empty!"
    exit 0 # don't exit with error code, could be a non-program-managed workspace (with respect to continuous deployment)
fi    

# overwrite old file and add disclaimer
echo "# DO NOT EDIT (generated)" > /opt/workspace_os_dependencies.txt
echo "#" >> /opt/workspace_os_dependencies.txt
echo "# This file is auto-generated by the write_osdeps.bash script" >> /opt/workspace_os_dependencies.txt
echo "# Install custom packages (e.g. editors) by adding them directly to the Dockerfile" >> /opt/workspace_os_dependencies.txt

list_autoproj_osdeps () {
    echo "adding dependencies of autoproj workspace folder: $(pwd)"
    . env.sh
    ruby /opt/list_rock_osdeps.rb >> /opt/workspace_os_dependencies.txt
}

list_ros_osdeps () {
    echo "adding dependencies of wstool workspace folder: $(pwd)"
    bash /opt/list_ros_osdeps.bash >> /opt/workspace_os_dependencies.txt
}

# make function available for bash used in find
export -f list_autoproj_osdeps
export -f list_ros_osdeps

# search for folder with an "autoproj" folder (autoproj buildconf) and add dependencies to file"
if [ ! -z "$(find -maxdepth 2 -type d -name autoproj)" ]; then
    find -type d -name autoproj -execdir bash -c 'list_autoproj_osdeps' \;
fi

# search for folder with a ".rosinstall" file and add dependencies to file"
if [ ! -z "$(find -maxdepth 2 -type d -name src)" ]; then
    find src/ -name .rosinstall -execdir bash -c 'list_ros_osdeps' \;
fi

echo
if cmp -s "/opt/installed_workspace_os_dependencies.txt" "/opt/workspace_os_dependencies.txt"; then
    echo "No new OS dependencies written"
else
    echo "Found new OS dependencies, please rebuild the devel image"
fi
echo
