#!/bin/bash

set -e

cd /opt/workspace
if [ -z $(find -type d -name autoproj) ] && [ -z $(find -type d -name src) ]; then
    echo "Neither autoproj nor ros workspace detected."
    [ -z "$(ls -A)" ] && echo "Your workspace directory is empty!"
    exit 1
fi    

# overwrite old file and add disclaimer
echo "# DO NOT EDIT (generated)" > /opt/workspace_os_dependencies.txt
echo "#" >> /opt/workspace_os_dependencies.txt
echo "# This file is auto-generated by the write_osdeps.bash script" >> /opt/workspace_os_dependencies.txt
echo "# Install custom packages (e.g. editors) by adding them directly to the Dockerfile" >> /opt/workspace_os_dependencies.txt

list_autoproj_osdeps () {
    echo "adding dependencies of autoproj workspace folder: $(pwd)"
    . env.sh
    ruby /opt/list_rock_osdeps.rb >> /opt/workspace_os_dependencies.txt
}

list_ros_osdeps () {
    echo "adding dependencies of wstool workspace folder: $(pwd)"
    bash /opt/list_ros_osdeps.bash >> /opt/workspace_os_dependencies.txt
}

# make function available for bash used in find
export -f list_autoproj_osdeps
export -f list_ros_osdeps

# search for folder with an "autoproj" folder (autoproj buildconf) and add dependencies to file"
find -type d -name autoproj -execdir bash -c 'list_autoproj_osdeps' \;

# search for folder with a ".rosinstall" file and add dependencies to file"
find src/ -name .rosinstall -execdir bash -c 'list_ros_osdeps' \;

echo
if cmp -s "/opt/installed_workspace_os_dependencies.txt" "/opt/workspace_os_dependencies.txt"; then
    echo "No new OS dependencies written"
else
    echo "Found new OS dependencies, please update the devel image"
fi
echo
TEST
