#!/bin/bash

. ./settings.bash

DEVEL_IMAGE=${DOCKER_REGISTRY:+${DOCKER_REGISTRY}/}$WORKSPACE_DEVEL_IMAGE
RELEASE_IMAGE=${DOCKER_REGISTRY:+${DOCKER_REGISTRY}/}$WORKSPACE_RELEASE_IMAGE


docker pull $DEVEL_IMAGE
docker pull $RELEASE_IMAGE
