#!/bin/bash

cd /opt/workspace
source env.sh
export BASE_LOG_LEVEL="ERROR"
rock-bundle-sel sherpa_tt_robdekon
#rock-launch -b waste_site_simulation_headless.cnd
#rock-launch -b waste_site_simulation.cnd
rock-launch -b halt.cnd

