#!/bin/bash
echo
echo "This file is needed for the Continuous Deployment feature."
echo "It should contain instructions to non-interactively build the workspace"
echo

cd /opt/workspace
source env.sh
amake
